server:
  port: 9002
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5  # 初始化连接数量，
    minIdle: 5        # 最小连接数
    maxActive: 50     # 最大连接数
    maxWait: 60000    # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 600000    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    #申请连接的时候检测
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    testOnReturn: false
    filters: stat,wall,log4j      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙,防止sql注入
    logSlowSql: true
    druid:
      user: admin
      password: admin
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        file-extension: yml
        server-addr: localhost:8848
        prefix: ${spring.application.name}

rocketmq:
  name-server: 127.0.0.1:9876
  topic: distributed-cache-topic
  producer:
    group: distributed-cache-producer-group
  consumer:
    group: distributed-cache-consumer-group

seata:
  service:
    vgroup-mapping:
      default_tx_group: default
    grouplist:
      #seata服务器ip
      default: 127.0.0.1:8091


#mybatis:
#  # 指定 mapper.xml 的位置
#  mapper-locations: classpath:mapper/*.xml
#  #扫描实体类的位置,在此处指明扫描实体类的包，在 mapper.xml 中就可以不写实体类的全路径名
#  type-aliases-package: com.zmm.entity
#  configuration:
#    #默认开启驼峰命名法，可以不用设置该属性
#    map-underscore-to-camel-case: true